//>>built
define("xstyle/core/parser",["xstyle/core/utils"],function(P){function J(){this.push.apply(this,arguments)}function K(f){this.value=f}function L(f,s,C){function D(t,r){function s(a){x=!1;var l=n.lastIndex;a.then(function(){x=!0;e&&(n.lastIndex=l,w())});var e=!0}function w(){function f(a){a&&("string"==typeof a&&w)&&(a=w+a);b?b.push?"string"==typeof b[b.length-1]&&"string"==typeof a?b[b.length-1]+=a:a&&b.push(a):"string"==typeof b&&"string"==typeof a?b+=a:b=new J(b,a):b=a}for(x=!0;x;){var q=n.exec(t);
if(!q)break;var e=q[5],w=q[1],c=q[2],g=q[3],h=q[4],k,m,b,E,h=h&&F(h),c=c&&F(c);u?(g?(m=c,k=g.charAt(0),E="?"==g.charAt(1),-1<g.indexOf("\n")&&(h=g.slice(1))):h=c,b=h,u=!1):(h=g?c+g:c,f(h));"{"!=e&&(l+=q[0]);switch(e){case "'":case '"':var y="'"==e?Q:R;y.lastIndex=n.lastIndex;e=y.exec(t);c=e[1];n.lastIndex=y.lastIndex;f(new K(c));l+=e[0];continue;case "\\":e=y.lastIndex++;f(t.charAt(e));continue;case "(":case "{":case "[":var d,M=!1;if("{"==e){u=!0;":"==k&&g&&(c+=g);l=F((l+c).replace(/\s+/g," ").replace(/([\.#:])\S+|\w+/g,
function(a,b){return b?a:a.toLowerCase()}));f(d=a.newRule(l));"\x3d"==k&&(z=!1,b.creating=!0,h&&(M=!0));":"==k&&!a.root&&(b.creating=!0);var g=null,I=A;if(q[6]){var G=r.cssRules||r.rules;if(d.cssRule=g=G[q[6].slice(1)])l=g.selectorText}if(a.root&&z)for(G=r.cssRules||r.rules;g=G[A++];)if(g.selectorText==l){d.cssRule=g;break}g||(d.ruleIndex=A=I,d.styleSheet=r);b.creating?(d.selector="."+("\x3d"==k?c.match(/[\w-]*$/g,"")[0]:"")+"-x-"+S++,d.creating=!0):d.selector=a.root?l:a.selector+" "+l;l=""}else c=
h.match(/(.*?)([\w-]*)$/),f(d=a.newCall(c[2],b,a)),d.ref=a.getDefinition(c[2]),(b.calls||(b.calls=[])).push(d);d.parent=a;M&&h.replace(/\s*([\w-]+)\s*$/g,function(a,b){var c=P.extend(d,b,C);c&&c.then&&s(c)});a.currentName=m;a.currentSequence=b;a.assignmentOperator=k;var B;if("{"==e&&(B=d.selector.match(/[@:]\w+/)))B=B[0],(m=a.getDefinition(B))&&m.selector&&m.selector(d);p.push(a=d);a.operator=e;a.start=n.lastIndex;b=m=null;continue}if(b)if(c="string"==typeof b?b:b[0],c.charAt&&"@"==c.charAt(0))if(h=
c.match(/\w+/)[0],"import"==h)c=L.getStyleSheet((r.cssRules||r.imports)[A++],b,r),h=n.lastIndex,D(c.localSource,c),n.lastIndex=h;else{if("xstyle"==h){if("start"==c.slice(8,13))d=a?a.newRule(""):N,d.root=a.root,d.parent=a,p.push(a=d);else{var N=a||N;p.pop();a=p[p.length-1]}n=a?O:/(@[\w\s])/g}}else if(k)try{var v=a[":"==k?"setValue":"declareProperty"](m,b,E);v&&v.then&&s(v)}catch(T){}switch(e){case ":":"\x3d"==k?(u=!0,k=":"):f(":");break;case "}":case ")":case "]":m=null;m=t.slice(a.start,n.lastIndex-
1);a.cssText=a.cssText?a.cssText+";"+m:m;if("}"==e){"}"==H&&(H=a.parent.selector)&&H.charAt(0);if(!a.root){try{a.onRule(a.selector,a)}catch(U){}z=!0}l=""}")"==e&&!k&&(a.args=b.isSequence?b:[b],(v=p[p.length-2].onCall(a))&&v.then&&s(v));p.pop();a=p[p.length-1];b=a.currentSequence;m=a.currentName;k=a.assignmentOperator;if(a.root&&"}"==e){if(k)try{a[":"==k?"setValue":"declareProperty"](m,b[1]||b,E)}catch(V){}u=!0;k=!1}break;case "":case void 0:return;case ";":b=null,u=!0,k=z=!1,l=""}var H=e}}function C(a){}
t=t.replace(I,function(a){return a.replace(/[^\n]/g,"")});var a=f;n.lastIndex=0;var x,A=0,z=!0,l="",u=!0;w()}var O,n=O=/(\s*)((?:[^{\}\[\]\(\)\\'":=;]|\[(?:[^\]'"]|'(?:\\.|[^'])*'|"(?:\\.|[^"])*")\])*)([=:]\??\s*([^{\}\[\]\(\)\\'":;]*))?(?:([{\}\[\]\(\)\\'":;])(\/\d+)?|$)/g,p=[f];f.parse=D;D(s,C)}var Q=/((?:\\.|[^'])*)'/g,R=/((?:\\.|[^"])*)"/g,I=/\/\*[\w\W]*?\*\//g,S=0,F="".trim?function(f){return f.trim()}:function(f){return f.replace(/^\s+|\s+$/g,"")},s=J.prototype=[];s.toString=function(){return this.join("")};
s.isSequence=!0;K.prototype.toString=function(){return'"'+this.value.replace(/["\\\n\r]/g,"\\$\x26")+'"'};return L});
//# sourceMappingURL=parser.js.map